[package]
name = "webrockets"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "webrockets"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.6", features = ["ws"] }
dashmap = "6.1"
axum-extra = { version = "0.12.1", features = ["typed-header"] }
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
fastwebsockets = { version = "0.10.0", features = ["unstable-split", "upgrade", "with_axum"] }
futures-util = { version = "0.3.31", features = ["sink"] }
headers = "0.4.1"
indexmap = "2"
log = "0.4.29"
pyo3 = "0.27.1"
pyo3-log = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "signal", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
pyo3-async-runtimes = { version = "0.27.0", features = ["tokio-runtime"] }
redis = { version = "0.27", features = ["tokio-comp"] }
lapin = { version = "2.5" }
uuid = { version = "1", features = ["v4"] }
async-trait = "0.1.89"
hyper = { version = "1.8.1", features = ["client", "http1"] }
hyper-util = { version = "0.1.19", features = ["tokio"] }
http-body-util = "0.1.3"
bytes = "1.11.0"
tokio-rustls = "0.26.4"
webpki-roots = "1.0.6"
rustls = { version = "0.23.37", features = ["ring"] }
rustls-platform-verifier = "0.6.2"
tokio-util = "0.7.18"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true

[tool.maturin]
python-source = "py"
