services:
  webrockets:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/webrockets/Dockerfile
    restart: unless-stopped

  webrockets-django:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/webrockets-django/Dockerfile
    restart: unless-stopped

  channels:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/channels/Dockerfile
    restart: unless-stopped

  fastapi:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/fastapi/Dockerfile
    restart: unless-stopped

  bolt:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/bolt/Dockerfile
    restart: unless-stopped

  websockets:
    network_mode: host
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    build:
      context: .
      dockerfile: servers/websockets/Dockerfile
    restart: unless-stopped
